# The version tag has been removed as it is now obsolete.

services:
  nextapp:
    build: .
    image: nextapp
    container_name: nextapp
    env_file:
      - .env.local
    ports:
      - "3000:3000"
      - "8000:8000"
    restart: unless-stopped